#  Phalcon Breadcrumbs
#
#  Copyright (c) 2016-2017, Phalcon Framework Team
#  (https://www.phalconphp.com)
#
#  This source file is subject to the New BSD License that is bundled
#  with this package in the file LICENSE.txt
#
#  If you did not receive a copy of the license and are unable to
#  obtain it through the world-wide-web, please send an email
#  to license@phalconphp.com so we can send you a copy immediately.
#
#  Authors: Serghei Iakovlev <serghei@phalconphp.com>

language: php

dist: trusty
sudo: false

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1

git:
    depth: 1

env:
    matrix:
        - PHALCON_VERSION="phalcon-v2.0.13"
        - PHALCON_VERSION="v3.2.0"

matrix:
    fast_finish: true
    exclude:
        - env: PHALCON_VERSION="phalcon-v2.0.13"
          php: 7.0
        - env: PHALCON_VERSION="phalcon-v2.0.13"
          php: 7.1

cache:
    apt: true
    timeout: 691200
    directories:
        - vendor
        - $HOME/.composer/cache

before_install:
    - phpenv config-rm xdebug.ini || true
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
    - travis_retry composer install --prefer-dist --no-interaction --ignore-platform-reqs
    - git clone -q --depth=1 https://github.com/phalcon/cphalcon.git -b ${PHALCON_VERSION}

install:
    - (cd cphalcon/build; bash install)
    - '[[ "${PHALCON_VERSION}" == "phalcon-v2.0.13" ]] || phpenv config-add cphalcon/tests/_ci/phalcon.ini'
    - '[[ "${PHALCON_VERSION}" != "phalcon-v2.0.13" ]] || phpenv config-add cphalcon/unit-tests/ci/phalcon.ini'

script:
    - vendor/bin/phpcs
    - vendor/bin/codecept build &> /dev/null
    - vendor/bin/codecept run

notifications:
    email:
        recipients:
            - build@phalconphp.com
        on_success: change
        on_failure: always
